#!/usr/bin/env python3
from package_one.module_one import IntegerAdder
from package_two.module_two import PublicIPAddress
from package_two.module_two import PublicIPAddressError

integer_adder = IntegerAdder()
result = integer_adder.add(21, 21)
print("The answer to life is {}.".format(result))

ip_address_getter = PublicIPAddress()
try:
    ip_address_getter.get_public_ip_address()
except PublicIPAddressError as error:
    print(error)
else:
    ip_address_getter.print_public_ip_address()
finally:
    ip_address_getter = None